services:
  - type: web
    name: api-consultoria
    env: node
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333

databases:
  - name: api-consultoria-db
    databaseName: api_consultoria
    user: api_consultoria_user
